# Generated by Django 6.0.6 on 2026-06-15 07:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('type', models.CharField(choices=[('group', 'Group'), ('dm', 'Direct')], default='group', max_length=10)),
                ('dm_model_id', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sender_type', models.CharField(choices=[('user', 'User'), ('ai', 'AI')], max_length=5)),
                ('sender_name', models.CharField(max_length=200)),
                ('model_id', models.CharField(blank=True, max_length=200)),
                ('provider', models.CharField(blank=True, max_length=20)),
                ('color', models.CharField(default='#a78bfa', max_length=20)),
                ('bg_color', models.CharField(default='rgba(108,71,255,0.2)', max_length=50)),
                ('initials', models.CharField(default='AI', max_length=4)),
                ('content', models.TextField()),
                ('tags', models.JSONField(default=list)),
                ('is_autonomous', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.room')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
