# Generated by Django 6.0.6 on 2026-06-15 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_id', models.CharField(max_length=200, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('provider', models.CharField(choices=[('groq', 'Groq'), ('openrouter', 'OpenRouter'), ('gemini', 'Gemini')], max_length=20)),
                ('is_free', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('color', models.CharField(default='#a78bfa', max_length=20)),
                ('bg_color', models.CharField(default='rgba(108,71,255,0.2)', max_length=50)),
                ('initials', models.CharField(default='AI', max_length=4)),
                ('last_synced', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['provider', 'name'],
            },
        ),
    ]
